### ISSUE TITLE
Using json-schema/OAS notation for write validation rules

### ISSUE THREAD

**Issue by funkill** [MathiasPius/yaml-validator#5]
Maybe better and simple for learning use json-schema or [OpenAPI Specification](https://swagger.io/specification/#schemaObject) (based on json-schema, section "Schema Object") for write validation schema?

**Comment by MathiasPius** [comment]
Thank you! I was not aware it was available as yaml as well, this will help immensely in fleshing out what the format should look like!

I'll see if I can try and direct the format in that direction. I'm trying to replace serde_yaml with yaml_rust at the moment since serde_yaml had no support for parsing multiple docs per string/file, but I'll definitely take a serious look at this once I'm done with that. :)

**Comment by MathiasPius** [comment]
Note to self: https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5

**Comment by MathiasPius** [comment]
Covered by: https://github.com/MathiasPius/yaml-validator/milestone/1
